export const countries = [
  { countryName: "Afghanistan", countryCode: "AF", callCode: "+93" },
  { countryName: "Albania", countryCode: "AL", callCode: "+355" },
  { countryName: "Algeria", countryCode: "DZ", callCode: "+213" },
  { countryName: "Andorra", countryCode: "AD", callCode: "+376" },
  { countryName: "Angola", countryCode: "AO", callCode: "+244" },
  { countryName: "Antigua and Barbuda", countryCode: "AG", callCode: "+1" },
  { countryName: "Argentina", countryCode: "AR", callCode: "+54" },
  { countryName: "Armenia", countryCode: "AM", callCode: "+374" },
  { countryName: "Australia", countryCode: "AU", callCode: "+61" },
  { countryName: "Austria", countryCode: "AT", callCode: "+43" },
  { countryName: "Azerbaijan", countryCode: "AZ", callCode: "+994" },
  { countryName: "Bahamas", countryCode: "BS", callCode: "+1" },
  { countryName: "Bahrain", countryCode: "BH", callCode: "+973" },
  { countryName: "Bangladesh", countryCode: "BD", callCode: "+880" },
  { countryName: "Barbados", countryCode: "BB", callCode: "+1" },
  { countryName: "Belarus", countryCode: "BY", callCode: "+375" },
  { countryName: "Belgium", countryCode: "BE", callCode: "+32" },
  { countryName: "Belize", countryCode: "BZ", callCode: "+501" },
  { countryName: "Benin", countryCode: "BJ", callCode: "+229" },
  { countryName: "Bhutan", countryCode: "BT", callCode: "+975" },
  { countryName: "Bolivia", countryCode: "BO", callCode: "+591" },
  { countryName: "Bosnia and Herzegovina", countryCode: "BA", callCode: "+387" },
  { countryName: "Botswana", countryCode: "BW", callCode: "+267" },
  { countryName: "Brazil", countryCode: "BR", callCode: "+55" },
  { countryName: "Brunei", countryCode: "BN", callCode: "+673" },
  { countryName: "Bulgaria", countryCode: "BG", callCode: "+359" },
  { countryName: "Burkina Faso", countryCode: "BF", callCode: "+226" },
  { countryName: "Burundi", countryCode: "BI", callCode: "+257" },
  { countryName: "Cabo Verde", countryCode: "CV", callCode: "+238" },
  { countryName: "Cambodia", countryCode: "KH", callCode: "+855" },
  { countryName: "Cameroon", countryCode: "CM", callCode: "+237" },
  { countryName: "Canada", countryCode: "CA", callCode: "+1" },
  { countryName: "Central African Republic", countryCode: "CF", callCode: "+236" },
  { countryName: "Chad", countryCode: "TD", callCode: "+235" },
  { countryName: "Chile", countryCode: "CL", callCode: "+56" },
  { countryName: "China", countryCode: "CN", callCode: "+86" },
  { countryName: "Colombia", countryCode: "CO", callCode: "+57" },
  { countryName: "Comoros", countryCode: "KM", callCode: "+269" },
  { countryName: "Congo (Congo-Brazzaville)", countryCode: "CG", callCode: "+242" },
  { countryName: "Costa Rica", countryCode: "CR", callCode: "+506" },
  { countryName: "Croatia", countryCode: "HR", callCode: "+385" },
  { countryName: "Cuba", countryCode: "CU", callCode: "+53" },
  { countryName: "Cyprus", countryCode: "CY", callCode: "+357" },
  { countryName: "Czechia (Czech Republic)", countryCode: "CZ", callCode: "+420" },
  { countryName: "Denmark", countryCode: "DK", callCode: "+45" },
  { countryName: "Djibouti", countryCode: "DJ", callCode: "+253" },
  { countryName: "Dominica", countryCode: "DM", callCode: "+1" },
  { countryName: "Dominican Republic", countryCode: "DO", callCode: "+1" },
  { countryName: "Ecuador", countryCode: "EC", callCode: "+593" },
  { countryName: "Egypt", countryCode: "EG", callCode: "+20" },
  { countryName: "El Salvador", countryCode: "SV", callCode: "+503" },
  { countryName: "Equatorial Guinea", countryCode: "GQ", callCode: "+240" },
  { countryName: "Eritrea", countryCode: "ER", callCode: "+291" },
  { countryName: "Estonia", countryCode: "EE", callCode: "+372" },
  { countryName: "Eswatini (fmr. Swaziland)", countryCode: "SZ", callCode: "+268" },
  { countryName: "Ethiopia", countryCode: "ET", callCode: "+251" },
  { countryName: "Fiji", countryCode: "FJ", callCode: "+679" },
  { countryName: "Finland", countryCode: "FI", callCode: "+358" },
  { countryName: "France", countryCode: "FR", callCode: "+33" },
  { countryName: "Gabon", countryCode: "GA", callCode: "+241" },
  { countryName: "Gambia", countryCode: "GM", callCode: "+220" },
  { countryName: "Georgia", countryCode: "GE", callCode: "+995" },
  { countryName: "Germany", countryCode: "DE", callCode: "+49" },
  { countryName: "Ghana", countryCode: "GH", callCode: "+233" },
  { countryName: "Greece", countryCode: "GR", callCode: "+30" },
  { countryName: "Grenada", countryCode: "GD", callCode: "+1" },
  { countryName: "Guatemala", countryCode: "GT", callCode: "+502" },
  { countryName: "Guinea", countryCode: "GN", callCode: "+224" },
  { countryName: "Guinea", countryCode: "GN", callCode: "+224" },
  { countryName: "Guinea-Bissau", countryCode: "GW", callCode: "+245" },
  { countryName: "Guyana", countryCode: "GY", callCode: "+592" },
  { countryName: "Haiti", countryCode: "HT", callCode: "+509" },
  { countryName: "Holy See", countryCode: "VA", callCode: "+379" },
  { countryName: "Honduras", countryCode: "HN", callCode: "+504" },
  { countryName: "Hungary", countryCode: "HU", callCode: "+36" },
  { countryName: "Iceland", countryCode: "IS", callCode: "+354" },
  { countryName: "India", countryCode: "IN", callCode: "+91" },
  { countryName: "Indonesia", countryCode: "ID", callCode: "+62" },
  { countryName: "Iran", countryCode: "IR", callCode: "+98" },
  { countryName: "Iraq", countryCode: "IQ", callCode: "+964" },
  { countryName: "Ireland", countryCode: "IE", callCode: "+353" },
  { countryName: "Israel", countryCode: "IL", callCode: "+972" },
  { countryName: "Italy", countryCode: "IT", callCode: "+39" },
  { countryName: "Jamaica", countryCode: "JM", callCode: "+1" },
  { countryName: "Japan", countryCode: "JP", callCode: "+81" },
  { countryName: "Jordan", countryCode: "JO", callCode: "+962" },
  { countryName: "Kazakhstan", countryCode: "KZ", callCode: "+7" },
  { countryName: "Kenya", countryCode: "KE", callCode: "+254" },
  { countryName: "Kiribati", countryCode: "KI", callCode: "+686" },
  { countryName: "Korea, North", countryCode: "KP", callCode: "+850" },
  { countryName: "Korea, South", countryCode: "KR", callCode: "+82" },
  { countryName: "Kosovo", countryCode: "XK", callCode: "+383" },
  { countryName: "Kuwait", countryCode: "KW", callCode: "+965" },
  { countryName: "Kyrgyzstan", countryCode: "KG", callCode: "+996" },
  { countryName: "Laos", countryCode: "LA", callCode: "+856" },
  { countryName: "Latvia", countryCode: "LV", callCode: "+371" },
  { countryName: "Lebanon", countryCode: "LB", callCode: "+961" },
  { countryName: "Lesotho", countryCode: "LS", callCode: "+266" },
  { countryName: "Liberia", countryCode: "LR", callCode: "+231" },
  { countryName: "Libya", countryCode: "LY", callCode: "+218" },
  { countryName: "Liechtenstein", countryCode: "LI", callCode: "+423" },
  { countryName: "Lithuania", countryCode: "LT", callCode: "+370" },
  { countryName: "Luxembourg", countryCode: "LU", callCode: "+352" },
  { countryName: "Madagascar", countryCode: "MG", callCode: "+261" },
  { countryName: "Malawi", countryCode: "MW", callCode: "+265" },
  { countryName: "Malaysia", countryCode: "MY", callCode: "+60" },
  { countryName: "Maldives", countryCode: "MV", callCode: "+960" },
  { countryName: "Mali", countryCode: "ML", callCode: "+223" },
  { countryName: "Malta", countryCode: "MT", callCode: "+356" },
  { countryName: "Marshall Islands", countryCode: "MH", callCode: "+692" },
  { countryName: "Mauritania", countryCode: "MR", callCode: "+222" },
  { countryName: "Mauritius", countryCode: "MU", callCode: "+230" },
  { countryName: "Mexico", countryCode: "MX", callCode: "+52" },
  { countryName: "Micronesia", countryCode: "FM", callCode: "+691" },
  { countryName: "Moldova", countryCode: "MD", callCode: "+373" },
  { countryName: "Monaco", countryCode: "MC", callCode: "+377" },
  { countryName: "Mongolia", countryCode: "MN", callCode: "+976" },
  { countryName: "Montenegro", countryCode: "ME", callCode: "+382" },
  { countryName: "Morocco", countryCode: "MA", callCode: "+212" },
  { countryName: "Mozambique", countryCode: "MZ", callCode: "+258" },
  { countryName: "Myanmar", countryCode: "MM", callCode: "+95" },
  { countryName: "Namibia", countryCode: "NA", callCode: "+264" },
  { countryName: "Nauru", countryCode: "NR", callCode: "+674" },
  { countryName: "Nepal", countryCode: "NP", callCode: "+977" },
  { countryName: "Netherlands", countryCode: "NL", callCode: "+31" },
  { countryName: "New Zealand", countryCode: "NZ", callCode: "+64" },
  { countryName: "Nicaragua", countryCode: "NI", callCode: "+505" },
  { countryName: "Niger", countryCode: "NE", callCode: "+227" },
  { countryName: "Nigeria", countryCode: "NG", callCode: "+234" },
  { countryName: "North Macedonia", countryCode: "MK", callCode: "+389" },
  { countryName: "Norway", countryCode: "NO", callCode: "+47" },
  { countryName: "Oman", countryCode: "OM", callCode: "+968" },
  { countryName: "Pakistan", countryCode: "PK", callCode: "+92" },
  { countryName: "Palau", countryCode: "PW", callCode: "+680" },
  { countryName: "Palestine State", countryCode: "PS", callCode: "+970" },
  { countryName: "Panama", countryCode: "PA", callCode: "+507" },
  { countryName: "Papua New Guinea", countryCode: "PG", callCode: "+675" },
  { countryName: "Paraguay", countryCode: "PY", callCode: "+595" },
  { countryName: "Paraguay", countryCode: "PY", callCode: "+595" },
  { countryName: "Peru", countryCode: "PE", callCode: "+51" },
  { countryName: "Philippines", countryCode: "PH", callCode: "+63" },
  { countryName: "Poland", countryCode: "PL", callCode: "+48" },
  { countryName: "Portugal", countryCode: "PT", callCode: "+351" },
  { countryName: "Qatar", countryCode: "QA", callCode: "+974" },
  { countryName: "Romania", countryCode: "RO", callCode: "+40" },
  { countryName: "Russia", countryCode: "RU", callCode: "+7" },
  { countryName: "Rwanda", countryCode: "RW", callCode: "+250" },
  { countryName: "Saint Kitts and Nevis", countryCode: "KN", callCode: "+1" },
  { countryName: "Saint Lucia", countryCode: "LC", callCode: "+1" },
  { countryName: "Saint Vincent and the Grenadines", countryCode: "VC", callCode: "+1" },
  { countryName: "Samoa", countryCode: "WS", callCode: "+685" },
  { countryName: "San Marino", countryCode: "SM", callCode: "+378" },
  { countryName: "Sao Tome and Principe", countryCode: "ST", callCode: "+239" },
  { countryName: "Saudi Arabia", countryCode: "SA", callCode: "+966" },
  { countryName: "Senegal", countryCode: "SN", callCode: "+221" },
  { countryName: "Serbia", countryCode: "RS", callCode: "+381" },
  { countryName: "Seychelles", countryCode: "SC", callCode: "+248" },
  { countryName: "Sierra Leone", countryCode: "SL", callCode: "+232" },
  { countryName: "Singapore", countryCode: "SG", callCode: "+65" },
  { countryName: "Slovakia", countryCode: "SK", callCode: "+421" },
  { countryName: "Slovenia", countryCode: "SI", callCode: "+386" },
  { countryName: "Solomon Islands", countryCode: "SB", callCode: "+677" },
  { countryName: "Somalia", countryCode: "SO", callCode: "+252" },
  { countryName: "South Africa", countryCode: "ZA", callCode: "+27" },
  { countryName: "South Sudan", countryCode: "SS", callCode: "+211" },
  { countryName: "Spain", countryCode: "ES", callCode: "+34" },
  { countryName: "Sri Lanka", countryCode: "LK", callCode: "+94" },
  { countryName: "Sudan", countryCode: "SD", callCode: "+249" },
  { countryName: "Suriname", countryCode: "SR", callCode: "+597" },
  { countryName: "Sweden", countryCode: "SE", callCode: "+46" },
  { countryName: "Switzerland", countryCode: "CH", callCode: "+41" },
  { countryName: "Syria", countryCode: "SY", callCode: "+963" },
  { countryName: "Taiwan", countryCode: "TW", callCode: "+886" },
  { countryName: "Tajikistan", countryCode: "TJ", callCode: "+992" },
  { countryName: "Tanzania", countryCode: "TZ", callCode: "+255" },
  { countryName: "Thailand", countryCode: "TH", callCode: "+66" },
  { countryName: "Timor-Leste", countryCode: "TL", callCode: "+670" },
  { countryName: "Togo", countryCode: "TG", callCode: "+228" },
  { countryName: "Tonga", countryCode: "TO", callCode: "+676" },
  { countryName: "Trinidad and Tobago", countryCode: "TT", callCode: "+1" },
  { countryName: "Tunisia", countryCode: "TN", callCode: "+216" },
  { countryName: "Turkey", countryCode: "TR", callCode: "+90" },
  { countryName: "Turkmenistan", countryCode: "TM", callCode: "+993" },
  { countryName: "Tuvalu", countryCode: "TV", callCode: "+688" },
  { countryName: "Uganda", countryCode: "UG", callCode: "+256" },
  { countryName: "Ukraine", countryCode: "UA", callCode: "+380" },
  { countryName: "United Arab Emirates", countryCode: "AE", callCode: "+971" },
  { countryName: "United Kingdom", countryCode: "GB", callCode: "+44" },
  { countryName: "United States of America", countryCode: "US", callCode: "+1" },
  { countryName: "Uruguay", countryCode: "UY", callCode: "+598" },
  { countryName: "Uzbekistan", countryCode: "UZ", callCode: "+998" },
  { countryName: "Vanuatu", countryCode: "VU", callCode: "+678" },
  { countryName: "Venezuela", countryCode: "VE", callCode: "+58" },
  { countryName: "Vietnam", countryCode: "VN", callCode: "+84" },
  { countryName: "Yemen", countryCode: "YE", callCode: "+967" },
  { countryName: "Zambia", countryCode: "ZM", callCode: "+260" },
  { countryName: "Zimbabwe", countryCode: "ZW", callCode: "+263" }
];
export interface ICountries{
  countryName:string
  countryCode:string
  callCode:string
}


export const Defaultcountry = { countryName: "Nigeria", countryCode: "NG", callCode: "+234" }